### ISSUE TITLE
Bug: Orb init isn't using the latest template from this repo due to missed versions?

### ISSUE THREAD

**Issue by adamdmharvey** [CircleCI-Public/Orb-Template#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Orb version

CircleCI CLI 0.1.22322+5ff92b4 (homebrew)

### Current behavior

When using `circleci orb init .`, it's provisioning an orb template using Orb Tools v11.1.  This repo however uses Orb Tools v11.3.

Seems that the CLI only considers properly released/tagged elements out of this repo:

https://github.com/CircleCI-Public/circleci-cli/blob/5ff92b4ddd64da789d351c1a070ef48340a23b41/cmd/orb.go#L1072

The most recent tag was in July (https://github.com/CircleCI-Public/Orb-Template/tags), but there were enhancements to this template in October (https://github.com/CircleCI-Public/Orb-Template/pull/7) to use the latest orb-tools.

I'd like to recommend a newer tag be released for this repo so users creating new orbs get the latest and greatest orb?

### Minimum reproduction config

n/a

**Comment by EricRibeiro** [comment]
Thanks for the heads-up, @adamdmharvey. I'll release a new version shortly.

**Comment by EricRibeiro** [comment]
Done! [v1.0.4](https://github.com/CircleCI-Public/Orb-Template/releases/tag/v1.0.4) is out.
